version: '3.1'

services:
  sut:
    build: .
    ports:
      - '3030:3030'
    environment:
      NODE_ENV: dev
      PORT: 3030
      DB_HOST: db-test
      DB_NAME: service_db
      DB_USERNAME: service_user
      DB_PASS: service_user_pass
      DB_PORT: 5432
    command: npm run test:fresh
    depends_on:
      - db-test
  db-test:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data-test:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: service_user_pass
      POSTGRES_USER: service_user
      POSTGRES_DB: service_db
