const studentCreateTableQuery = `-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE student (
    id text PRIMARY KEY UNIQUE,
    first_name text NOT NULL,
    last_name text NOT NULL,
    age smallint,
    state text,
    create_date timestamp with time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX student_pkey ON student(id text_ops);
CREATE UNIQUE INDEX student_id_key ON student(id text_ops);

`;
